# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45f7d9e23f1d479a55ceba3d65600bc696cbe3c938a232e6737af8d317679936a9a9382e475fff4d365d6cab5b1247d91cbb70b51d432a819d9239a46619bba3

test:
  secret_key_base: 3b5dff84c76aee1fc6e8b4e44d8432901bfb3cb27696c1eae76f59f29931fd84c59206ce87569349a3118c35c62dc6935cf5c762adbe89e9d4919aa39a19d316

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
